### ISSUE TITLE
IAPI Module Entries Filter Issue

### ISSUE THREAD

**Issue by tbcorr** [photoncms/cms#20]
Photon v1.1.0

Inside of class **FilterModuleEntriesDecoder**, function _getAllDynamicModuleEntries_ is being passed **$includeRelations** as a parameter. However the function signature does not include this parameter resulting in a mismatch of parameter values. **$filters** becomes Null and **$sorting** becomes the value of **$filters**. This is resulting in Query Builder errors when I attempt to filter module entries.

I modified the _getAllDynamicModuleEntries_ call in **FilterModuleEntriesDecoder** by removing the **$includeRelations** parameter and filtering now appears to be working as expected.

**Comment by tihomiro** [comment]
Thanks, fixed in v.1.1.1.
