### ISSUE TITLE
.png upload resize issue. 

### ISSUE THREAD

**Issue by kirstencates7shifts** [photoncms/cms#24]
When you upload a .png file and the file is run through the default image resizer it adds a background colour to the .png. 
![original](https://user-images.githubusercontent.com/39278325/43803341-dc382000-9a55-11e8-882f-cea4d1e966b9.png)
![thumbnail-created](https://user-images.githubusercontent.com/39278325/43803342-dc4f946a-9a55-11e8-88b9-bdc9775891e6.png)

**Comment by tihomiro** [comment]
When using GD Library the transparency is lost while transforming PNGs with an alpha channel. Use Imagick library instead. The change is made in the .env file (https://photoncms.com/resources/configuration#configuring-the-env-file). Essentially, just change these two lines like so:

`# IMAGE_SOFTWARE=GD
IMAGE_SOFTWARE=Imagick`
