### ISSUE TITLE
Unable to install on Windows (pcntl extension)

### ISSUE THREAD

**Issue by creazy231** [photoncms/cms#35]
I tried to install photoncms on my windows machine.
I followed the installation guide and I'm not able to pass the following error:
```
Problem 1
    - laravel/horizon v1.4.3 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
```
Is there anything I can do without setting up a virtual linux machine?

**Comment by arkid** [comment]
This is a really annoying limitation, is there no way around this ?

**Comment by tihomiro** [comment]
laravel/horizon is not essential for Photon CMS to function, so you can just remove that line from composer.json and run `composer install` again.

We'll remove this dependency in the next release.

**Comment by arkid** [comment]
Thank you!  I know windows based development not on LAMP isn't what most want to do but sometimes its a necessity so this will be most appreciated!
