### ISSUE TITLE
I have created some modules but no menu items ar visible 

### ISSUE THREAD

**Issue by douma** [photoncms/cms#37]
![](https://i.imgur.com/i3hRbxL.png)

**Comment by tihomiro** [comment]
Menu items are created manually using the Menu Editor > Menu Items Editor option from the main menu.

**Comment by douma** [comment]
The cause: I accidently overwrote the menu_items table with the module generator.

**Comment by tihomiro** [comment]
Menu Items is a Photon module, just like any other Photon module, and it can be extended and customized, and even deleted as Photon CMS is a headless system. We will consider adding some protection mechanisms so that you can't alter the system modules as easy as now.
