### ISSUE TITLE
Postgres?

### ISSUE THREAD

**Issue by rmiller335** [photoncms/cms#42]
Hi.  I would like to run Photon with Postres.  I made the changes in .env and config/database.php, but when I run php artisan photon:hard-reset I get SQLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration parameter "tables" (SQL: SHOW TABLES), so I think Photon still thinks it's talking to a MySQL database.  Is there documentation somewhere that describes how to use Photon with Postres?

Thanks,
Bob Miller

**Comment by tihomiro** [comment]
Hi Bob, I'm afraid that Photon CMS is tightly coupled with MySQL.
