### ISSUE TITLE
Asset Filesystem issue

### ISSUE THREAD

**Issue by neosin** [photoncms/cms#8]
Fresh install on XAMPP latest
**2 issues with assets both probably related to paths?**

**1.** logged in and clicked "asset manager"
tried to upload an image and it does upload however it displays as broken.
No error logs in API log.
this is the path it displays
http://127.0.0.1:8080/storage/assets/test_image.png

**2.** created a content type and added an asset content field
tried creating a record and uploading an image asset.
Receive "Error uploading image"
API log shows response_data message "IMAGE_FACTORY_DOESNT_EXIST"
However the image does indeed exist in the storage folder.

in **filesystems.php** it is using the default
`        // Assets local Photon storage
        'assets' => [
            'driver' => 'local',
            'root'   => storage_path('app/public/assets'),
            'path'   => "/storage/assets",
        ],`

Project folder setup:
/photon/public <---- Apache Doc Root
/photon/storage/app/public/assets <---- images files are here

any ideas whats going on?
I assume this is a paths issue with windows systems?

**Comment by NightfallSD** [comment]
Hi neosin. 

1. Have you run `php artisan storage:link` in you application root? 
2. What is value of your IMAGE_SOFTWARE variable from .env file? And do you have selected softvare (GD or Imagick) installed?

**Comment by neosin** [comment]
1. yes I ran the storage link and it had no issues
2. IMAGE_SOFTWARE=GD, GD is installed
besides this, it seems everything else works

**Comment by neosin** [comment]
hmmm, I found this bug report in laravel about filesystem that seems to affect many people and appears to be related to my issue

https://github.com/laravel/framework/issues/13610

**Comment by neosin** [comment]
I ran the storage link command again, this is the output
> $ php artisan storage:link
> Local NTFS volumes are required to complete the operation.
> The [public/storage] directory has been linked.
but the issue persists

**Comment by neosin** [comment]
Ok found the issue. Even though artisan didn't show errors, the symlinks didn't create due to the dev system drive being fat32 format. It works fine on ntfs drive.
Hours of my life I will never get back lol.

**Comment by tihomiro** [comment]
Glad you've found it! :) Are you still receiving "Error uploading image" error (issue #2) or that's been solved too?

**Comment by neosin** [comment]
it was part of the same issue, they both used the symlink

**Comment by tihomiro** [comment]
Thanks, closing.
